### ISSUE TITLE
Some possible suggestions...

### ISSUE THREAD

**Issue by mgcaret** [Patrick-Barry/emu65816#1]
I was poking around for an '816 emulator core, and happened across yours. 😄 It looks somewhat promising for what I want to do (emulate a hypothetical system).  I was about to resort to writing my own, but I hate to re-invent the wheel.

I know you are pretty early into this, and you might have your own objectives for this project, so feel free to take this message or leave it.   I have used some other emulator cores and found some things I liked and things I didn't when trying to build a system with them.

One thing I liked was the ability to define my own memory map via function pointers.

So by simple extension of your existing interface, the client code of your emulation core would do something like this

```
  int memory_read(*state, unsigned int address);
  void memory_write(*state, unsigned int address, int data);
  
  Boot65816(&cpu, &memory_read, &memory_write);
```

No need for a clear memory flag because you've either done that or not done that yourself.  state is a just a means of providing the emulator state (probably just the 'cpu' structure) to the functions so that they can get at bus signals (RDY, ML, M/X, VPA, VDA, etc.), trigger interrupts, simulate wait states, assert signals (RDY, ABORTB, etc.), and such.

A major advantage of this is that the client code can emulate the hardware independently of what the CPU core is doing. 

Another thing I liked was being able to run the emulator for a specific number of cycles and have it stop.  In this case you'd provide an initialization function, a reset function, and a run function like such:

```
  executed_cycles = Run65816(&cpu, requested_cycles)
```

Assuming no exceptions, after the given number of cycles the function returns (it may not be exact, as instructions should complete, amongst other reasons.)  It might also return because the STP, WAI, or WDM instructions were executed, or some other scenario.

This can be used with some other hypothetical functions to provide some system-level things that might happen, such as periodic interrupts (Irq65816(...), Nmi65816(...), etc.).  It can also provide a means to add debugging checkpoints and such, or even single-step the emulator (by always asking for 1 cycle).

I once used a Z80 emulator with this sort of interface to build a CP/M emulator in Ruby that was still reasonably fast because the emulator core was in C, most of the memory was simply malloced, and since the Z80 uses separate I/O address space, the entire CP/M BIOS and BDOS was implemented in Ruby code and accessed from within the emulator via OUT instructions (one might conceivably do something similar with the '816 COP or WDM instruction).  The Ruby code translated the calls to access the normal unix file system it was running on as drives (via directories named drive_a, drive_b, etc).   Of course the ruby code cheated bigtime and proceeded to manipulate the RAM and registers directly before returning.  But it worked like a charm.

**Comment by Patrick-Barry** [comment]
I appreciate your comments and suggestions and really like the idea of using function pointers for the memory read/write functions.  I started this project with a specific idea in mind so my plan was to just modify my current memory read/write functions for the specific memory map I plan on using. Your suggestion for the functions being passed I hadn't considered when I started, but I really like the idea.

I decided to use a struct to keep track of the CPU state and have it passed to all the functions that need to update/read it. Although my project won't need it I figured this would allow multiple CPU cores to be run at the same time. I think I may modify the struct to hold function pointers for the memory read/write functions so that each CPU state structure is capable of using its own memory map. 

My Execute65816() function was designed from the start to take the number of cycles to run and return the actual number it did run. I've seen this design in 6502 emulators for timing when to execute NMI. Also like you said it also makes single stepping through the program trivial by always requesting 1 cycle to run. It will also make it easier to debug the core for cycle accurate timing of the instructions. Since I will know exactly how many cycles it took that one instruction to run.
